### ISSUE TITLE
import pysit error

### ISSUE THREAD

**Issue by simonlegrand** [pysit/pysit#22]
Hello,

Thanks for upgrading the installation procedure and porting the code to python3.
I work on Ubuntu16.04 with a conda environment under python3.6. I followed your instructions and at the importing time I get the following error:

$ python
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/slegrand/pysit/pysit/__init__.py", line 28, in <module>
    from pysit.solvers import *
  File "/home/slegrand/pysit/pysit/solvers/__init__.py", line 1, in <module>
    from .wave_factory import *
  File "/home/slegrand/pysit/pysit/solvers/wave_factory.py", line 3, in <module>
    from .constant_density_acoustic import(ConstantDensityAcousticTimeODE_1D,
  File "/home/slegrand/pysit/pysit/solvers/constant_density_acoustic/__init__.py", line 3, in <module>
    from .time import *
  File "/home/slegrand/pysit/pysit/solvers/constant_density_acoustic/time/__init__.py", line 4, in <module>
    from .scalar import *
  File "/home/slegrand/pysit/pysit/solvers/constant_density_acoustic/time/scalar/__init__.py", line 1, in <module>
    from .constant_density_acoustic_time_scalar_1D import *
  File "/home/slegrand/pysit/pysit/solvers/constant_density_acoustic/time/scalar/constant_density_acoustic_time_scalar_1D.py", line 15, in <module>
    from ._constant_density_acoustic_time_scalar_cpp import (
ModuleNotFoundError: No module named 'pysit.solvers.constant_density_acoustic.time.scalar._constant_density_acoustic_time_scalar_cpp'

Have ever encountered this error?

Best regards,

Simon

**Comment by rhewett** [comment]
Hi Simon,

Are you in the pysit repository directory?

If so, you can't import from there, you have to be in a different directory.  This is usually where these sorts of errors come from.

**Comment by simonlegrand** [comment]
Thank you, indeed I was in pysit directory! Do you have an explanation about this behavior? I have probably missed some mechanism about python import system, but I don't understand why I can import it from anywhere else than the pysit folder.

**Comment by rhewett** [comment]
Yes, when you try to `import pysit`, it is trying to import the local directory `pysit` as a module, it is not going to the site packages to get the installed version.  That local directory looks alot like a module because it contains the files that get copied to the installation location, but the c++ codes are not compiled to this directory, they are compiled to the installation directory.  Thus, the import fails when trying to find the modules.

**Comment by rhewett** [comment]
No problem!  If you can, email me offline and let me know what sort of things you are using the package for.

And please submit issues as they arise!

**Comment by zchenCN** [comment]
I also encounter this problem, thanks a lot
