### ISSUE TITLE
Error when installing pysit on windows

### ISSUE THREAD

**Issue by A-Safwan** [pysit/pysit#41]
Hello,

I am trying to install pysit on windows device, using Anaconda Prompt with the following command: "pip install pysit"
also tried "pip install pysit --pre", it didn't work. I hope you can help me with this issue.
I have all the dependencies, but I always get an error, which I am copying below(In between ### lines):

##################################################################
 Using cached pysit-0.5b3.zip (1.7 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-a664fd4c\\pysit_668b199a5a72491b93621975d0894500\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-a664fd4c\\pysit_668b199a5a72491b93621975d0894500\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-wet1ept4'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-a664fd4c\pysit_668b199a5a72491b93621975d0894500\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-a664fd4c\pysit_668b199a5a72491b93621975d0894500\setup.py", line 50, in <module>
        extensions = [Extension(key, **value) for key, value in extension_config.iteritems()]
    AttributeError: 'dict' object has no attribute 'iteritems'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/40/5d/024f04efa9b28787f2f49bd8a9a9a5e212e90801131e7908ac81b1660954/pysit-0.5b3.zip#sha256=203d3da58b75be284ebd9106fbd7aed9c1cd881375ee2121d38b03660a30597d (from https://pypi.org/simple/pysit/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pysit-0.5b2.zip (482 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-a664fd4c\\pysit_069f81ee07cf4eb992a7dfe94df5f8a9\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-a664fd4c\\pysit_069f81ee07cf4eb992a7dfe94df5f8a9\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-xpb45_t9'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-a664fd4c\pysit_069f81ee07cf4eb992a7dfe94df5f8a9\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-a664fd4c\pysit_069f81ee07cf4eb992a7dfe94df5f8a9\setup.py", line 50, in <module>
        extensions = [Extension(key, **value) for key, value in extension_config.iteritems()]
    AttributeError: 'dict' object has no attribute 'iteritems'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/21/c2/fae22c700ef8c404431a03014a0097c10dbe6d0a2b96b945d8e91a5960b3/pysit-0.5b2.zip#sha256=91f6969c4a5458eff9c4224a61ca31b09e4089a61f66ed64dc7e9b70031aad39 (from https://pypi.org/simple/pysit/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pysit-0.5b1.zip (279 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\user\anaconda3\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-a664fd4c\\pysit_a632dcce94704760840b58b43cbbaaf2\\setup.py'"'"'; __file__='"'"'C:\\Users\\USER\\AppData\\Local\\Temp\\pip-install-a664fd4c\\pysit_a632dcce94704760840b58b43cbbaaf2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\USER\AppData\Local\Temp\pip-pip-egg-info-mf3_o0z_'
         cwd: C:\Users\USER\AppData\Local\Temp\pip-install-a664fd4c\pysit_a632dcce94704760840b58b43cbbaaf2\
    Complete output (31 lines):
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.14.tar.gz
    Traceback (most recent call last):
      File "c:\users\user\anaconda3\lib\site-packages\ez_setup.py", line 143, in use_setuptools
        raise ImportError
    ImportError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\USER\AppData\Local\Temp\pip-install-a664fd4c\pysit_a632dcce94704760840b58b43cbbaaf2\setup.py", line 11, in <module>
        ez_setup.use_setuptools()
      File "c:\users\user\anaconda3\lib\site-packages\ez_setup.py", line 145, in use_setuptools
        return _do_download(version, download_base, to_dir, download_delay)
      File "c:\users\user\anaconda3\lib\site-packages\ez_setup.py", line 123, in _do_download
        tarball = download_setuptools(version, download_base,
      File "c:\users\user\anaconda3\lib\site-packages\ez_setup.py", line 193, in download_setuptools
        src = urlopen(url)
      File "c:\users\user\anaconda3\lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "c:\users\user\anaconda3\lib\urllib\request.py", line 531, in open
        response = meth(req, response)
      File "c:\users\user\anaconda3\lib\urllib\request.py", line 640, in http_response
        response = self.parent.error(
      File "c:\users\user\anaconda3\lib\urllib\request.py", line 569, in error
        return self._call_chain(*args)
      File "c:\users\user\anaconda3\lib\urllib\request.py", line 502, in _call_chain
        result = func(*args)
      File "c:\users\user\anaconda3\lib\urllib\request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: SSL is required
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d4/06/5364d54017f6358d7c5c9d591f324364978dabacda59cab5119860e0d34a/pysit-0.5b1.zip#sha256=fe4d2a2ed8081f6e335069a4676ff847f4d5f02c6b19e7dc7c9d5886021446c0 (from https://pypi.org/simple/pysit/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pysit (from versions: 0.5b1, 0.5b2, 0.5b3)
ERROR: No matching distribution found for pysit

##################################################################

**Comment by rhewett** [comment]
The issue seems to be that the version on PyPI is old and requires Python 2.  You are likely (and correctly) using Python 3.

If you install from source (clone the github repo) you should not have this issue.
