### ISSUE TITLE
patch option in marmousi2 ?

### ISSUE THREAD

**Issue by jdb666** [pysit/pysit#42]
Hi,  I am trying to use the patch option with the marmousi2 model : 

   C, C0, m, d = marmousi2(initial_model_style='smooth_low_pass', pixel_scale='mini',patch='fracture-square') 

I get an error (marmousi  1 works fine) : 

Traceback (most recent call last):
  File "Fcam1-l2.py", line 32, in <module>
    exec(open("../mcamL.py").read())
  File "<string>", line 4, in <module>
  File "/home/benamou/PYSIT/pysit/pysit/gallery/marmousi2.py", line 121, in marmousi2
    C, C0, m, d = MarmousiModel2(**model_config).get_setup()
  File "/home/benamou/PYSIT/pysit/pysit/gallery/gallery_base.py", line 336, in __init__
    self.rebuild_models()
  File "/home/benamou/PYSIT/pysit/pysit/gallery/gallery_base.py", line 345, in rebuild_models
    parameter_arrays = [self._load_scaled_parameter_array(p) for p in parameter_names]
  File "/home/benamou/PYSIT/pysit/pysit/gallery/gallery_base.py", line 345, in <listcomp>
    parameter_arrays = [self._load_scaled_parameter_array(p) for p in parameter_names]
  File "/home/benamou/PYSIT/pysit/pysit/gallery/gallery_base.py", line 628, in _load_scaled_parameter_array
    self._write_npy(arr, scaled_parameter_path)
  File "/home/benamou/PYSIT/pysit/pysit/gallery/gallery_base.py", line 493, in _write_npy

  Thanks for your help 
JD

**Comment by rhewett** [comment]
Are you able to load the full model, without patches?

**Comment by jdb666** [comment]
Yes also with mpi and several shots

**Comment by rhewett** [comment]
Hmm.  I've just tested this (mini-square appears to have an issue) but fracture-square is working OK for me.  It almost looks like there is an issue caching the patch (or loading the cached patch).

Try clearing that cache (usually in `~/.pysit/gallery_data`.  

If that doesn't fix it, can you share a bit more about the issue?  (Also try a different patch, maybe `left-layers-square`.)
* What version of PySIT and Python
* The full error stack, I don't see what the actual exception is here
* An MRE (including MPI config if need be)

**Comment by jdb666** [comment]
Hi Russel 
Thanks for the info. 


  fracture-square indeed works.

I think I diagnosed something : 

  water_properties = ('depth', 473.0) #m, see Marmousi2, an elasticc upgrade for Marmousi
                'mini-square' : {'origin': np.array([3950+195*24.0, 440.0]),
                                 'size': np.array([128*24.0, 128*24.0])},

Is broken 
But 

 water_properties = ('depth', 473.0) #m, see Marmousi2, an elasticc upgrade for Marmousi
                'mini-square' : {'origin': np.array([3950+195*24.0, 0.0]),
                                 'size': np.array([128*24.0, 128*24.0])},

Works  so it may be something with the z coordinate of the origin of the patch.

Regards 
JD
